### PR TITLE
kmartin/Add support for RFC1123 Date/Time in Retry-After header.

### PR DESCRIPTION
**Pull request by kevinmartin**
# What?
* The `Retry-After` header can have a numerical value that denotes how long a client should wait before retrying or a date/time value that denotes when a client a client should retry.
* This PR adds the ability to attempt to parse a date/time value if it is non-numerical.

### CODE REVIEW

**Comment by Opelord** [comment]
Hey, is this feature going to be merged soon?

**Comment by justenwalker** [comment]
I opened #144 for discussion about the feature. Given that there are now 3 PRs that accomplish the same thing, we should probably consolidate discussion in a single place.

**Comment by manicminer** [comment]
@kevinmartin Thanks for submitting this PR. I appreciate this has been outstanding for a long time, however I'm going to merge #138 for this functionality as that has additional safety checks on the resulting duration after parsing. Thanks again for working on this.

**Comment by manicminer** [comment]
Duplicate of #138

**Pull request closed without merging**
